title: Cloud Native Warrior
description: Training programme to help one jump start into cloud native.
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
  repository_url: github.com/cloudape
  owner_url: github.com/pyx7b
